seoTitle: 'Афиша, расписание концертов, купить билеты в ДК Железнодорожников в Екатеринбурге'
seoKeywords: 'афиша, концерты, расписание, дк железнодорожников'
seoDescription: 'На сайте ДК Железнодорожников вы сможете купить билеты на все концерты. В разделе "Афиша" вы найдете расписание концертов.'
